ci(sdks): reusable step to build openapi spec
Signed-off-by: Antonio Pedro Vieira <apsvieira95@gmail.com>

diff --git a/.github/workflows/publish-packages.yml b/.github/workflows/publish-packages.yml
--- a/.github/workflows/publish-packages.yml
+++ b/.github/workflows/publish-packages.yml
@@ -20,7 +20,7 @@ on:
         type: boolean
 
 jobs:
-  publish:
+  publish-python-packages:
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -28,16 +28,6 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '18'
-          registry-url: 'https://npm.pkg.github.com'
-
-      - name: Install root dependencies
-        run: |
-          cd frontend
-          npm ci
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -50,9 +40,33 @@ jobs:
           pip install 'uv<0.8'
           uv sync
 
-      - name: Render OpenAPI Specification
+      - name: Build Python Packages
         run: |
-          uv run python scripts/export-openapi.py --out ./generated/openapi.json
+          uv build --wheel --all
+
+      - name: Publish Python Packages
+        uses: actions/upload-artifact@v4
+        with:
+          name: python-packages
+          path: dist
+          if-no-files-found: error
+
+  generate-openapi-spec:
+    uses: ./.github/workflows/reusable/openapi-build-spec.yml
+    # with:
+    #   force_publish: ${{ github.event.inputs.force_publish }}
+
+  publish-frontend-packages:
+    runs-on: ubuntu-latest
+    needs: generate-openapi-spec
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Retrieve OpenAPI spec
+        run: |
+          mkdir -p ${{ github.workspace }}/generated
+          touch ${{ github.workspace }}/generated/openapi.json
+          echo ${{ needs.generate-openapi-spec.outputs.spec }} > ${{ github.workspace }}/generated/openapi.json
 
       - name: Generate new client
         run: |
@@ -63,7 +77,7 @@ jobs:
             -g typescript-fetch \
             --additional-properties=modelPropertyNaming=original \
             -o /local/generated/ts
-
+            
       - name: Copy generated files
         run: |
           set -x
@@ -71,15 +85,17 @@ jobs:
           cp -r ${{ github.workspace }}/generated/ts/* ${{ github.workspace }}/frontend/packages/client-open/src/
           ls -la ${{ github.workspace }}/frontend/packages/client-open/src/
 
+      # Build & Publish Frontend Packages
       - name: Build all packages
         run: |
           cd frontend
           npm run build
 
-      - name: Publish packages
+      - name: Publish development version of packages
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_publish == 'true')
+        # Only publish development version of packages on non-main, non-release refs
+        if: (github.event_name == 'push' && github.ref != 'refs/heads/main' && github.ref != 'refs/tags/v*')
         run: |
           cd frontend/packages
 
@@ -91,10 +107,11 @@ jobs:
 
             # Check if package version already exists
             PACKAGE_NAME=$(node -p "require('./package.json').name")
-            PACKAGE_VERSION=$(node -p "require('./package.json').version")
+            PACKAGE_VERSION="${{ github.sha }}"
 
             if npm view "$PACKAGE_NAME@$PACKAGE_VERSION" > /dev/null 2>&1; then
-              echo "Package $PACKAGE_NAME@$PACKAGE_VERSION already exists, skipping..."
+              echo "Package $PACKAGE_NAME@$PACKAGE_VERSION already exists, failing..."
+              exit 1
             else
               npm publish
               echo "Published $PACKAGE_NAME@$PACKAGE_VERSION"
